# syntax=docker/dockerfile:1.4
FROM python:3.12-alpine
RUN adduser -D microblog

WORKDIR /home/microblog

# COPY . .
COPY app app
COPY migrations migrations
COPY requirements requirements
COPY requirements.txt microblog.py boot.sh ./

RUN python -m venv .venv; .venv/bin/pip3 install -r requirements.txt

ENV FLASK_APP=microblog.py

RUN chmod +x boot.sh; chown -R microblog:microblog ./

USER microblog

HEALTHCHECK --interval=30s --timeout=5s --start-period=5s \
  CMD curl -f http://localhost:5000 || exit 1

EXPOSE 5000
ENTRYPOINT ["./boot.sh"]
